package com.renalize.android.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0865FE)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDBE1FF)
val onPrimaryContainerLight = Color(0xFF00184A)
val secondaryLight = Color(0xFF585E72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDDE1F9)
val onSecondaryContainerLight = Color(0xFF151B2C)
val tertiaryLight = Color(0xFF745471)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD6F8)
val onTertiaryContainerLight = Color(0xFF2B122B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE2E2EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF757680)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB3C5FF)
